export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_ASSET = "ADD_ASSET";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_ASSET = "DELETE_ASSET";
export const UPDATE_EMPLOYEE_NAME = "UPDATE_EMPLOYEE_NAME";
export const UPDATE_ASSET="UPDATE_ASSET";
export const UPDATE_ADDRESS_AND_PHONENUMBER = "UPDATE_ADDRESS_AND_PHONENUMBER";
export const RETRIEVE_EMPLOYEE = "RETRIEVE_EMPLOYEE";